package HelloApp;


/**
* HelloApp/HelloOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from Hello.idl
* Segunda-feira, 11 de Junho de 2001 22h44min05s BRT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
