/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Teste */

#ifndef _Included_Teste
#define _Included_Teste
#ifdef __cplusplus
//extern "C" {
#endif
/*
 * Class:     Teste
 * Method:    foo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Teste_foo
  (JNIEnv *, jclass);

#ifdef __cplusplus
//}
#endif
#endif